name: Lint and Tests

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Run linter
      run: docker-compose run app sh -c "flake8"
    - name: Run test suite
      run: |
         docker-compose run app sh -c "
         python manage.py wait_for_db && python manage.py test"